.TH "Birthday" 3 "Вс 12 Фев 2023" "Version 1.0.0.1" "Student" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Birthday
.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "void \fBSetDay\fP (unsigned char \fBday\fP)"
.br
.RI "Create methods\&. "
.ti -1c
.RI "unsigned char \fBGetDay\fP ()"
.br
.RI "GetDay method to get the student's birthday\&. "
.ti -1c
.RI "void \fBSetMonth\fP (unsigned char month)"
.br
.RI "SetMonth method to send or replace the student's month of birth\&. "
.ti -1c
.RI "unsigned char \fBGetMonth\fP ()"
.br
.RI "The GetMonth method is designed to get the month of the student's birth\&. "
.ti -1c
.RI "void \fBSetYear\fP (unsigned char year)"
.br
.RI "The SetYear method is designed to remove or replace the student's year of birth\&. "
.ti -1c
.RI "unsigned char \fBGetYear\fP ()"
.br
.RI "The GetYear method is designed to get the student's year of birth\&. "
.in -1c
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "unsigned char \fBday\fP"
.br
.RI "Create variables to store day, month and year of birth\&. "
.ti -1c
.RI "unsigned char \fBmonth\fP"
.br
.ti -1c
.RI "unsigned short \fByear\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле \fBBirthday\&.h\fP строка \fB2\fP
.SH "Методы"
.PP 
.SS "unsigned char Birthday::GetDay ()"

.PP
GetDay method to get the student's birthday\&. 
.PP
\fBВозвращает\fP
.RS 4
Day
.RE
.PP

.PP
См\&. определение в файле \fBBirthday\&.cpp\fP строка \fB17\fP
.SS "unsigned char Birthday::GetMonth ()"

.PP
The GetMonth method is designed to get the month of the student's birth\&. 
.PP
\fBВозвращает\fP
.RS 4
Month
.RE
.PP

.PP
См\&. определение в файле \fBBirthday\&.cpp\fP строка \fB33\fP
.SS "unsigned char Birthday::GetYear ()"

.PP
The GetYear method is designed to get the student's year of birth\&. 
.PP
\fBВозвращает\fP
.RS 4
Year
.RE
.PP

.PP
См\&. определение в файле \fBBirthday\&.cpp\fP строка \fB49\fP
.SS "void Birthday::SetDay (unsigned char day)"

.PP
Create methods\&. SetDay method to send or replace date of birth\&.
.PP
SetDay method to send or replace date of birth
.PP
\fBАргументы\fP
.RS 4
\fIday\fP \fBBirthday\fP
.RE
.PP
.PP
\fBАргументы\fP
.RS 4
\fIday\fP \fBBirthday\fP
.RE
.PP

.PP
См\&. определение в файле \fBBirthday\&.cpp\fP строка \fB9\fP
.SS "void Birthday::SetMonth (unsigned char month)"

.PP
SetMonth method to send or replace the student's month of birth\&. 
.PP
\fBАргументы\fP
.RS 4
\fImonth\fP Month
.RE
.PP

.PP
См\&. определение в файле \fBBirthday\&.cpp\fP строка \fB25\fP
.SS "void Birthday::SetYear (unsigned char year)"

.PP
The SetYear method is designed to remove or replace the student's year of birth\&. 
.PP
\fBАргументы\fP
.RS 4
\fIyear\fP 
.RE
.PP

.PP
См\&. определение в файле \fBBirthday\&.cpp\fP строка \fB41\fP
.SH "Данные класса"
.PP 
.SS "unsigned char Birthday::day"

.PP
Create variables to store day, month and year of birth\&. 
.PP
См\&. определение в файле \fBBirthday\&.h\fP строка \fB8\fP
.SS "unsigned char Birthday::month"

.PP
См\&. определение в файле \fBBirthday\&.h\fP строка \fB9\fP
.SS "unsigned short Birthday::year"

.PP
См\&. определение в файле \fBBirthday\&.h\fP строка \fB10\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для Student из исходного текста\&.
